// packages/sub-svelte/src/App.svelte
<script>
  import "./app.css";
  import { Router, Link, Route } from "svelte-routing";
  import Home from "./pages/Home.svelte";
  import Details from "./pages/Userdetail.svelte";
  import About from "./pages/About.svelte";
  export let url = "";
  export let basepath = "/sub-svelte";
</script>

<Router basepath={basepath} {url}>
  <nav class="bg-gray-100 dark:bg-gray-700 border-b border-gray-200 ">
    <div class="px-4 py-3">
      <div class="flex items-center">
        <ul class="flex flex-row font-medium mt-0 space-x-8 rtl:space-x-reverse text-sm">
          <li>
            <Link
              class="text-gray-900 dark:text-white hover:underline w-6 h-5 flex"
              to="/sub-svelte/"
            >
            <svg viewBox="0 0 32 32" xmlns="http://www.w3.org/2000/svg" fill="#000000"><g id="SVGRepo_bgCarrier" stroke-width="0"></g><g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g><g id="SVGRepo_iconCarrier"><title>file_type_svelte</title><path d="M26.47,5.7A8.973,8.973,0,0,0,14.677,3.246L7.96,7.4a7.461,7.461,0,0,0-3.481,5.009,7.686,7.686,0,0,0,.8,5.058,7.358,7.358,0,0,0-1.151,2.8,7.789,7.789,0,0,0,1.4,6.028,8.977,8.977,0,0,0,11.794,2.458L24.04,24.6a7.468,7.468,0,0,0,3.481-5.009,7.673,7.673,0,0,0-.8-5.062,7.348,7.348,0,0,0,1.152-2.8A7.785,7.785,0,0,0,26.47,5.7" style="fill:#ff3e00"></path><path d="M14.022,26.64A5.413,5.413,0,0,1,8.3,24.581a4.678,4.678,0,0,1-.848-3.625,4.307,4.307,0,0,1,.159-.61l.127-.375.344.238a8.76,8.76,0,0,0,2.628,1.274l.245.073-.025.237a1.441,1.441,0,0,0,.271.968,1.63,1.63,0,0,0,1.743.636,1.512,1.512,0,0,0,.411-.175l6.7-4.154a1.366,1.366,0,0,0,.633-.909,1.407,1.407,0,0,0-.244-1.091,1.634,1.634,0,0,0-1.726-.622,1.509,1.509,0,0,0-.413.176l-2.572,1.584a4.934,4.934,0,0,1-1.364.582,5.415,5.415,0,0,1-5.727-2.06A4.678,4.678,0,0,1,7.811,13.1,4.507,4.507,0,0,1,9.9,10.09l6.708-4.154a4.932,4.932,0,0,1,1.364-.581A5.413,5.413,0,0,1,23.7,7.414a4.679,4.679,0,0,1,.848,3.625,4.272,4.272,0,0,1-.159.61l-.127.375-.344-.237a8.713,8.713,0,0,0-2.628-1.274l-.245-.074.025-.237a1.438,1.438,0,0,0-.272-.968,1.629,1.629,0,0,0-1.725-.622,1.484,1.484,0,0,0-.411.176l-6.722,4.14a1.353,1.353,0,0,0-.631.908,1.394,1.394,0,0,0,.244,1.092,1.634,1.634,0,0,0,1.726.621,1.538,1.538,0,0,0,.413-.175l2.562-1.585a4.9,4.9,0,0,1,1.364-.581,5.417,5.417,0,0,1,5.728,2.059,4.681,4.681,0,0,1,.843,3.625A4.5,4.5,0,0,1,22.1,21.905l-6.707,4.154a4.9,4.9,0,0,1-1.364.581" style="fill:#fff"></path></g></svg>
            </Link>
          </li>
          <li>
            <Link
              class="text-gray-900 dark:text-white hover:underline"
              to="/sub-svelte/"
            >
              Users
            </Link>
          </li>
          <li>
            <Link
              class="text-gray-900 dark:text-white hover:underline"
              to="/sub-svelte/about"
            >
              About
            </Link>
          </li>
          <li>
            <Link
              class="text-gray-900 dark:text-white hover:underline"
              to="/sub-svelte/nothing-here"
            >
              Nothing Here
            </Link>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <Route component={Home}></Route>
  <Route path="/user/:id" let:params>
    <Details id={params.id}></Details>
  </Route>
  <Route  path="/about" component={About}></Route>
</Router>

// packages/sub-solidjs/src/App.tsx
import type { Component } from "solid-js";
import { Link, useRoutes, useLocation } from "@solidjs/router";

import { routes } from "./routes";

const App: Component = () => {
  const location = useLocation();
  const Route = useRoutes(routes);

  return (
    <>
      <nav class="bg-gray-100 dark:bg-gray-700 border-b border-gray-200 ">
        <div class="px-4 py-3">
          <div class="flex items-center">
            <ul class="flex flex-row font-medium mt-0 space-x-8 rtl:space-x-reverse text-sm">
              <li>
                <Link
                  class="text-gray-900 dark:text-white hover:underline w-7 h-6 flex"
                  href="/"
                >
                  <svg
                    data-hk="00000000010000000102000202021130"
                    class="w-9 h-9 -mt-1 text-link dark:text-link-dark "
                    width="100%"
                    height="100%"
                    xmlns="http://www.w3.org/2000/svg"
                    viewBox="0 0 166 155.3"
                  >
                    <defs>
                      <linearGradient
                        id="a"
                        gradientUnits="userSpaceOnUse"
                        x1="27.5"
                        y1="3"
                        x2="152"
                        y2="63.5"
                      >
                        <stop offset=".1" stop-color="#76b3e1"></stop>
                        <stop offset=".3" stop-color="#dcf2fd"></stop>
                        <stop offset="1" stop-color="#76b3e1"></stop>
                      </linearGradient>
                      <linearGradient
                        id="b"
                        gradientUnits="userSpaceOnUse"
                        x1="95.8"
                        y1="32.6"
                        x2="74"
                        y2="105.2"
                      >
                        <stop offset="0" stop-color="#76b3e1"></stop>
                        <stop offset=".5" stop-color="#4377bb"></stop>
                        <stop offset="1" stop-color="#1f3b77"></stop>
                      </linearGradient>
                      <linearGradient
                        id="c"
                        gradientUnits="userSpaceOnUse"
                        x1="18.4"
                        y1="64.2"
                        x2="144.3"
                        y2="149.8"
                      >
                        <stop offset="0" stop-color="#315aa9"></stop>
                        <stop offset=".5" stop-color="#518ac8"></stop>
                        <stop offset="1" stop-color="#315aa9"></stop>
                      </linearGradient>
                      <linearGradient
                        id="d"
                        gradientUnits="userSpaceOnUse"
                        x1="75.2"
                        y1="74.5"
                        x2="24.4"
                        y2="260.8"
                      >
                        <stop offset="0" stop-color="#4377bb"></stop>
                        <stop offset=".5" stop-color="#1a336b"></stop>
                        <stop offset="1" stop-color="#1a336b"></stop>
                      </linearGradient>
                    </defs>
                    <path
                      d="M163 35S110-4 69 5l-3 1c-6 2-11 5-14 9l-2 3-15 26 26 5c11 7 25 10 38 7l46 9 18-30z"
                      fill="#76b3e1"
                    ></path>
                    <path
                      d="M163 35S110-4 69 5l-3 1c-6 2-11 5-14 9l-2 3-15 26 26 5c11 7 25 10 38 7l46 9 18-30z"
                      opacity=".3"
                      fill="url(#a)"
                    ></path>
                    <path
                      d="m52 35-4 1c-17 5-22 21-13 35 10 13 31 20 48 15l62-21S92 26 52 35z"
                      fill="#518ac8"
                    ></path>
                    <path
                      d="m52 35-4 1c-17 5-22 21-13 35 10 13 31 20 48 15l62-21S92 26 52 35z"
                      opacity=".3"
                      fill="url(#b)"
                    ></path>
                    <path
                      d="M134 80a45 45 0 0 0-48-15L24 85 4 120l112 19 20-36c4-7 3-15-2-23z"
                      fill="url(#c)"
                    ></path>
                    <path
                      d="M114 115a45 45 0 0 0-48-15L4 120s53 40 94 30l3-1c17-5 23-21 13-34z"
                      fill="url(#d)"
                    ></path>
                  </svg>
                </Link>
              </li>
              <li>
                <Link
                  class="text-gray-900 dark:text-white hover:underline"
                  href="/"
                >
                  Users
                </Link>
              </li>
              <li>
                <Link
                  class="text-gray-900 dark:text-white hover:underline"
                  href="/about"
                >
                  About
                </Link>
              </li>
              <li>
                <Link
                  class="text-gray-900 dark:text-white hover:underline"
                  href="/nothing-here"
                >
                  Nothing Here
                </Link>
              </li>
            </ul>
          </div>
        </div>
      </nav>
      <main>
        <Route />
      </main>
    </>
  );
};

export default App;
